import type { ImageCatalogEntry } from '@/types/image';

/**
 * Tier 1 image catalog — high-impact images that appear above-the-fold
 * or on frequently visited pages.
 *
 * The build script (`scripts/optimize-images.ts`) reads this catalog to
 * generate responsive WebP variants and LQIP blur placeholders.
 *
 * To add an image:
 *   1. Add an entry here with accurate `width` / `height` from the source file.
 *   2. Run `npm run optimize-images` to regenerate the manifest.
 *   3. Use `<OptimizedImage imageName="your-key" />` in the component.
 */
export const IMAGE_CATALOG: readonly ImageCatalogEntry[] = [
  // ── Benefits section (EN) ──────────────────────────────────────────
  {
    name: 'benefit-1',
    src: '/images/benefit1.jpg',
    width: 544,
    height: 436,
    sizes: '(max-width: 768px) 85vw, 544px',
    alt: 'Bnoon fertility benefit — convenient and fast consultations',
    category: 'benefit',
  },
  {
    name: 'benefit-2',
    src: '/images/benefit2.jpg',
    width: 544,
    height: 436,
    sizes: '(max-width: 768px) 85vw, 544px',
    alt: 'Bnoon fertility benefit — certified doctors',
    category: 'benefit',
  },
  {
    name: 'benefit-3',
    src: '/images/benefit3.jpg',
    width: 544,
    height: 436,
    sizes: '(max-width: 768px) 85vw, 544px',
    alt: 'Bnoon fertility benefit — private and secure platform',
    category: 'benefit',
  },

  // ── Blog / clinic cards (EN) ───────────────────────────────────────
  {
    name: 'blog-riyadh',
    src: '/images/blog/bnoon-riyadh.avif',
    width: 378,
    height: 204,
    sizes: '(max-width: 768px) 330px, 450px',
    alt: 'Bnoon fertility clinic — Riyadh location',
    category: 'blog',
  },
  {
    name: 'blog-jeddah',
    src: '/images/blog/bnoon-jeddah.avif',
    width: 375,
    height: 208,
    sizes: '(max-width: 768px) 330px, 450px',
    alt: 'Bnoon fertility clinic — Jeddah location',
    category: 'blog',
  },
  {
    name: 'blog-king-salman',
    src: '/images/blog/king-salman.avif',
    width: 378,
    height: 205,
    sizes: '(max-width: 768px) 330px, 450px',
    alt: 'Bnoon fertility clinic — King Salman Road, Riyadh',
    category: 'blog',
  },
  {
    name: 'blog-alahsa',
    src: '/images/blog/bnoon-alahsa-img.jpg',
    width: 418,
    height: 250,
    sizes: '(max-width: 768px) 330px, 450px',
    alt: 'Bnoon fertility clinic — Al Ahsa location',
    category: 'blog',
  },

  // ── Page banners (EN) ──────────────────────────────────────────────
  {
    name: 'banner-bg',
    src: '/images/banner/banner-bg.jpg',
    width: 1920,
    height: 978,
    sizes: '100vw',
    alt: 'Bnoon hero banner background',
    category: 'banner',
  },
  {
    name: 'banner-hero',
    src: '/images/banner/banner.jpg',
    width: 1200,
    height: 1320,
    sizes: '(max-width: 768px) 100vw, 50vw',
    alt: "Bnoon hero banner — fertility and women's health",
    category: 'banner',
  },
  {
    name: 'aboutus-banner',
    src: '/images/aboutus.jpg',
    width: 1470,
    height: 329,
    sizes: '100vw',
    alt: 'Bnoon about us page banner',
    category: 'banner',
  },
  {
    name: 'clinics-banner',
    src: '/images/clinics-banner.jpg',
    width: 1470,
    height: 329,
    sizes: '100vw',
    alt: 'Bnoon clinics page banner',
    category: 'banner',
  },
  {
    name: 'experts-banner',
    src: '/images/experts-banner.jpg',
    width: 1470,
    height: 329,
    sizes: '100vw',
    alt: 'Bnoon experts page banner',
    category: 'banner',
  },
  {
    name: 'contact-us-banner',
    src: '/images/contact-us-banner.jpg',
    width: 1470,
    height: 329,
    sizes: '100vw',
    alt: 'Bnoon contact us page banner',
    category: 'banner',
  },
  {
    name: 'feedback-banner',
    src: '/images/feedback-banner.jpg',
    width: 1470,
    height: 329,
    sizes: '100vw',
    alt: 'Bnoon feedback page banner',
    category: 'banner',
  },
  {
    name: 'fertility-guide-banner',
    src: '/images/fertility-guid-banner.jpg',
    width: 1470,
    height: 329,
    sizes: '100vw',
    alt: 'Bnoon fertility guide page banner',
    category: 'banner',
  },

  // ── Page banners (AR) ─────────────────────────────────────────────
  {
    name: 'aboutus-banner-ar',
    src: '/images/aboutus-ar-banner.avif',
    width: 1470,
    height: 329,
    sizes: '100vw',
    alt: 'بنون — صفحة من نحن',
    category: 'banner',
  },
  {
    name: 'clinics-banner-ar',
    src: '/images/clinics-banner-ar.jpg',
    width: 1470,
    height: 329,
    sizes: '100vw',
    alt: 'بنون — صفحة العيادات',
    category: 'banner',
  },
  {
    name: 'experts-banner-ar',
    src: '/images/experts-banner-ar.jpg',
    width: 1470,
    height: 329,
    sizes: '100vw',
    alt: 'بنون — صفحة الخبراء',
    category: 'banner',
  },
  {
    name: 'contact-us-banner-ar',
    src: '/images/contactus-banner-ar.jpg',
    width: 1470,
    height: 329,
    sizes: '100vw',
    alt: 'بنون — صفحة اتصل بنا',
    category: 'banner',
  },
  {
    name: 'feedback-banner-ar',
    src: '/images/feedback-banner-ar.jpg',
    width: 1470,
    height: 329,
    sizes: '100vw',
    alt: 'بنون — صفحة التقييم',
    category: 'banner',
  },
  {
    name: 'fertility-guide-banner-ar',
    src: '/images/fertility-guid-banner-ar.jpg',
    width: 1470,
    height: 329,
    sizes: '100vw',
    alt: 'بنون — دليل الخصوبة',
    category: 'banner',
  },
  {
    name: 'join-team-banner-ar',
    src: '/images/join-our-team-ar.jpg',
    width: 1470,
    height: 329,
    sizes: '100vw',
    alt: 'بنون — انضم لفريقنا',
    category: 'banner',
  },

  // ── About / misc section images ────────────────────────────────────
  {
    name: 'bg-doctors',
    src: '/images/bg-doctors.jpg',
    width: 1665,
    height: 1600,
    sizes: '(max-width: 768px) 100vw, 50vw',
    alt: 'Bnoon doctors background',
    category: 'about',
  },
  {
    name: 'hear-patient',
    src: '/images/hear-patient.jpg',
    width: 1920,
    height: 1484,
    sizes: '100vw',
    alt: 'Bnoon patient testimonial background',
    category: 'about',
  },
  {
    name: 'fertility-women',
    src: '/images/fertility-women.jpg',
    width: 636,
    height: 461,
    sizes: '(max-width: 768px) 100vw, 636px',
    alt: "Fertility and women's health",
    category: 'about',
  },
  {
    name: 'baby-health-network',
    src: '/images/baby-health-network.jpg',
    width: 636,
    height: 460,
    sizes: '(max-width: 768px) 100vw, 636px',
    alt: 'Baby health network',
    category: 'about',
  },
  {
    name: 'baby-health-network-2',
    src: '/images/baby-health-network-2.jpg',
    width: 636,
    height: 460,
    sizes: '(max-width: 768px) 100vw, 636px',
    alt: 'Baby health network — secondary',
    category: 'about',
  },
  {
    name: 'fertility-doc',
    src: '/images/fertility-doc.avif',
    width: 517,
    height: 547,
    sizes: '(max-width: 768px) 100vw, 517px',
    alt: 'Bnoon fertility doctor',
    category: 'about',
  },

  // ── Service cards ──────────────────────────────────────────────────
  {
    name: 'ivf',
    src: '/images/ivf.jpg',
    width: 286,
    height: 210,
    sizes: '(max-width: 768px) 50vw, 286px',
    alt: 'IVF treatment at Bnoon',
    category: 'service',
  },
  {
    name: 'icsi',
    src: '/images/icsi.jpg',
    width: 286,
    height: 210,
    sizes: '(max-width: 768px) 50vw, 286px',
    alt: 'ICSI treatment at Bnoon',
    category: 'service',
  },
  {
    name: 'egg-freezing',
    src: '/images/egg-freezing.jpg',
    width: 286,
    height: 210,
    sizes: '(max-width: 768px) 50vw, 286px',
    alt: 'Egg freezing services at Bnoon',
    category: 'service',
  },
  {
    name: 'embryo-freezing',
    src: '/images/embryo-freezing.jpg',
    width: 286,
    height: 210,
    sizes: '(max-width: 768px) 50vw, 286px',
    alt: 'Embryo freezing services at Bnoon',
    category: 'service',
  },
  {
    name: 'fertility-counselling',
    src: '/images/fertility-counselling.jpg',
    width: 286,
    height: 210,
    sizes: '(max-width: 768px) 50vw, 286px',
    alt: 'Fertility counselling at Bnoon',
    category: 'service',
  },
] as const;
